---
name: Run Unit Tests

'on':
  - pull_request
  - push

env:
  SETUP_ENVTEST_VERSION: 8c5081a9b6ba

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: Install package and dependencies
        run: |
          GOBIN=$PWD go install sigs.k8s.io/controller-runtime/tools/setup-envtest@${{ env.SETUP_ENVTEST_VERSION }}
      - name: Install k8s
        run: |
          ./setup-envtest use 1.35 -p path
          ./setup-envtest list
      - name: Run tests
        run: |
          export KUBEBUILDER_ASSETS=`./setup-envtest use 1.35 -p path`
          go test -coverprofile=coverage.out -covermode=atomic -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
