---
name: Run Unit Tests

'on':
  - pull_request
  - push

env:
  SETUP_ENVTEST_VERSION: 8c5081a9b6ba

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install package and dependencies
        run: |
          GOBIN=$PWD go install sigs.k8s.io/controller-runtime/tools/setup-envtest@${{ env.SETUP_ENVTEST_VERSION }}
      - name: Install k8s
        run: |
          ./setup-envtest use 1.35 -p path
          ./setup-envtest list
      - name: Run tests
        run: |
          export KUBEBUILDER_ASSETS=`./setup-envtest use 1.35 -p path`
          go test -coverprofile=coverage.out -covermode=atomic -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
