---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:

  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.12'
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install package and dependencies
        run: |
          GOBIN=$PWD go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - name: Install k8s
        run: |
          ./setup-envtest use 1.24 -p path
          ./setup-envtest list
      - name: Run tests
        run: |
          export KUBEBUILDER_ASSETS=`./setup-envtest use 1.24 -p path`
          go test -v ./...
